$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
words:
  - guiiai
  - iconify
  - indexeddb
  - logg
  - pinia
  - shiki
  - shikijs
  - taze
  - unocss
  - xsai
