/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BranchFlow: typeof import('./components/BranchFlow.vue')['default']
    BranchView: typeof import('./components/BranchView.vue')['default']
    ChatFlow: typeof import('./components/ChatFlow.vue')['default']
    ChatHistory: typeof import('./components/ChatHistory.vue')['default']
    ChatThread: typeof import('./components/ChatThread.vue')['default']
    MessageNode: typeof import('./components/MessageNode.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
